# Generated by Django 4.1 on 2023-10-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0002_alter_pokemon_height_alter_pokemon_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='height',
            new_name='altura',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='weight',
            new_name='peso',
        ),
    ]
