# Generated by Django 4.1 on 2023-10-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0003_rename_height_pokemon_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='altura',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='peso',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
